export { CapabilityError, capabilityError, CAPABILITY_ERROR_CODES } from './errors.js';
export type { CapabilityErrorCode } from './errors.js';
export * from './types.js';
export * from './validation.js';
export * from './evaluate.js';
export * from './projection.js';
export * from './reliance.js';
export * from './bearcaps.js';
export * from './delegation-graph.js';
export * from './ucan-mapping.js';
export * from './proof-registry.js';
export * from './trust-registry.js';
export * from './vc-authority-binding.js';
export * from './authority-profiles.js';
